### ISSUE TITLE
build with GHC 8.4

### ISSUE THREAD

**Issue by jkachmar** [maoe/viewprof#11]
viewprof-0.0.0.14 fails to build with GHC 8.4 due to a restrictive upper bound on `base`:
```
base-4.11.0.0 is out of bounds for:
- [ ] viewprof-0.0.0.14 (>=4.9 && < 4.11). Mitsutoshi Aoe <maoe@foldr.in> @maoe. @maoe. Used by: executable
```

**Comment by maoe** [comment]
Fixed in https://hackage.haskell.org/package/viewprof-0.0.0.15
