### ISSUE TITLE
Allow brick <0.27

### ISSUE THREAD

**Issue by rhofour** [maoe/viewprof#6]
Brick 0.25 and 0.26 added new functions without breaking backwards compatibility. You should be able to safely extend your version bounds.

This is currently blocking the availability of brick-0.26 on Stackage: fpco/stackage#2933

**Comment by maoe** [comment]
Will fix it in a day or two.

**Comment by maoe** [comment]
Done as https://hackage.haskell.org/package/viewprof-0.0.0.9
